image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - felixfbecker.php-debug

tasks:
  - name: open browser
    command: gp open index.php